### PR TITLE
Default filters

### LINKED ISSUE #137: 💡 Feature request: Default filters
## Describe the feature you would like to be implemented
I would like to have default filters for subreddits, similarly to how there are default subs in the .env file. 

An example would be REDLIB_DEFAULT_FILTERED=politics+politicalhumor etc...

## Describe alternatives you've considered

I know they can be filtered user by user, however this is inconvenient unfortunately. I am the only one to use the instance, but I do use it across multiple browsers, so not having to set filters on each one would be great.

### PR DESCRIPTION
**Pull request by ac615223s5**
closes  #137

### CODE REVIEW

**Comment by sigaloid** [comment]
Is it just me, or do I not see any code that actually implements the filter? :face_with_peeking_eye:

**Comment by sigaloid** [comment]
Where's the code that actually uses the value in the config, to filter out subs?

**Comment by sigaloid** [comment]
AH!!! It's the cookie-default type of setting. Always slips my mind. Thanks so much for the PR! Happy to merge once the clippy lint passes :)

**Comment by zunjae** [comment]
A great feature that isn't advertised in the readme (unless im blind)

**Pull request merged**
